import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import Sidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "Souq Payment Gateway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col justify-between min-h-screen">
      <div>
        <Navbar />
        <div className="flex">
          <Sidebar />
          <div className="">{children}</div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
