import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Souq Payment Gateway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>Homenav</div>
      <div>{children}</div>
    </>
  );
}
